### ISSUE TITLE
[Feature Request] Rendering additional components

### ISSUE THREAD

**Issue by sorxrob** [rgommezz/react-native-scroll-bottom-sheet#18]
Hi, thanks for this awesome component. It's really smooth! This isn't an issue so pardon me for not following the issue format.

So I am trying to clone an app:

![Webp net-resizeimage](https://user-images.githubusercontent.com/13049130/85190253-0ccb5e00-b2e9-11ea-8d86-8f25ab4e7bf9.jpg)

This can easily be done by react-native-maps + this awesome component.

Looking at the example, inside the bottom sheet, there is a horizontal scrollable list of chips. If I want to mimic that functionality inside `react-native-scroll-bottom-sheet`, do I have to add it in the `renderHandle` prop? Or is there a better way of doing this?

Thanks!

**Comment by sorxrob** [comment]
I was able to clone it. Added the chips in the `renderHandle` prop.

![Screen Shot 2020-06-20 at 12 03 28 PM](https://user-images.githubusercontent.com/13049130/85190753-10adaf00-b2ee-11ea-93f5-8281c12da136.png)

**Comment by rgommezz** [comment]
Hey @sorxrob, many thanks for the kind words! 🎉 

Exactly, if you want the horizontal chips to be clipped at the top all the time, you have to use the `renderHandle` prop, whereas if you prefer to make it scrollable along with the content, then it'd be better to use [`ListHeaderComponent`](https://reactnative.dev/docs/flatlist#listheadercomponent) prop from `FlatList`.

I am closing this for now since you seem to have found a solution :)
