### ISSUE TITLE
Use spring instead of timing

### ISSUE THREAD

**Issue by harterc1** [rgommezz/react-native-scroll-bottom-sheet#4]
You should consider using `react-native-reanimated` `spring` instead of `timing`.

https://software-mansion.github.io/react-native-reanimated/spring.html

You can use the gesture's velocity as a starting velocity so that the bottomsheet snaps to a snap point at a natural speed & momentum -- better user experience.

**Comment by rgommezz** [comment]
Hi @harterc1,

I already take velocity into account to determine what the next snap point should be, but having a `Easing.Linear` function probably wasn't the best default of choice since it doesn't feel very natural. 

I agree that adding the possibility of having a `spring` animation driver could come in handy for extending the animations range. Will take a look soon.

In the meantime, you can configure the animation by providing a duration and/or a different easing function, via `animationConfig`. Have you tried [that](https://github.com/rgommezz/react-native-scroll-bottom-sheet#props)?

Some references:
Visualisation of common easing functions: https://easings.net/
Easing options `reanimated` exposes: https://github.com/software-mansion/react-native-reanimated/blob/1701f3947f4f5cf5350203a06c2845c55601c406/src/Easing.js

**Comment by tankers746** [comment]
I've created a PR for this! https://github.com/rgommezz/react-native-scroll-bottom-sheet/pull/36

**Comment by rgommezz** [comment]
Thanks to both @tankers746 and @dcoulter45 spring animations support has landed on version [0.7.0](https://github.com/rgommezz/react-native-scroll-bottom-sheet/releases/tag/v0.7.0)! 🚀
