### ISSUE TITLE
Orientation changes

### ISSUE THREAD

**Issue by djorkaeffalexandre** [rgommezz/react-native-scroll-bottom-sheet#6]
Hey @rgommezz, really thanks about this implementation, it's saving me a lot, is the most useful and updated library to do bottom sheet at react-native.
Can you provide some tips about the orientation mode changes?
My main idea was use https://github.com/wcandillon/react-native-responsive-ui and change the snapPoints when the orientation change, but it's not working fine, this library has limitations about the snapPoints changes while it's showing?
Thanks in advance.
Good weekend.

**Comment by rgommezz** [comment]
Hi @djorkaeffalexandre,

You are welcome, glad you found it useful!

I think your best shot at the moment is to remount the component on orientation changes, so that the library can process the new snapping points.

For that, you can use a `key` prop on the `ScrollBottomSheet` that varies on orientation changes. This is a react feature whereby you can force a remount on a component. Some pseudocode to help you get started:

```js
const OrientationAware = () => {
	// Custom hook that returns 'portrait' or 'landscape'
	// You can build it with `useDimensions` from that library
	const orientation = useOrientation();
	const snapPoints = {
		portrait: [...],
		landscape: [...]
	}

	return (
      <ScrollBottomSheet
 		key={orientation}
        componentType="FlatList"
        snapPoints={snapPoints[orientation]}
        initialSnapIndex={2}
        ...
      />
	);
}
```

Hope that helps!

**Comment by djorkaeffalexandre** [comment]
Hey @rgommezz, it helped me a lot.
I'll use the same issue but it's a different doubt, how I can archive a behavior like a bounce at the animation when it reach the top?
